@echo off
echo Starting Traumedy Backend Server...
cd /d "d:\Mini Project\traumedy\traumedy-backend"
echo Installing dependencies...
npm install
echo Starting server on port 8080...
node index.js
pause
